#!/usr/bin/env bash
# Write a bash script that Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)

# Checking that domain argument is provided
if [ $# -lt 1 ]; then
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi

domain=$1
subdomain=${2:-"www lb-01 web-01 web-02"}

# Looping  through subdomains and displaying their DNS records
for sd in $subdomain; do
  rec=$(dig +short $sd.$domain)
  if [ -n "$rec" ]; then
    echo "The subdomain $sd is a $(dig +short $sd.$domain | awk '{print $1}') record and points to $rec"
  fi
done
