#!/usr/bin/env bash
# This script sets up a redirect for the Nginx web server

# Install Nginx if it's not already installed
if ! command -v nginx &> /dev/null
then
    sudo apt-get update
    sudo apt-get install nginx -y
fi

# Create a new configuration file for Nginx
sudo bash -c "cat > /etc/nginx/sites-available/redirect.conf" << EOF
server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Enable the new configuration by creating a symlink
sudo ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/

# Check the syntax of the configuration files
sudo nginx -t

# Reload Nginx to apply the new configuration
sudo nginx -s reload
