#!/usr/bin/env bash
# write a  script that  configures Nginx on an Ubuntu machine.

# Updating  the package list
apt-get update

# Installing Nginx
apt-get install -y nginx

# Configuring  Nginx
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location / {
        return 200 'Hello World!';
    }
}
" > /etc/nginx/sites-available/default

# modify ngix configuration file
sudo sed -i '/http {/a \        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restarting  Nginx
service nginx restart

