#!/usr/bin/env bash

# Add custom HTTP response header to Nginx configuration
sudo sed -i 's/http {/http {\n    add_header X-Served-By $hostname;/' /etc/nginx/nginx.conf

# Restart Nginx service
sudo service nginx restart
