#!/usr/bin/env bash
# Installs and setup haproxy

# Install HAproxy
sudo apt-get -y update
sudo apt-get -y install

# Configure HAproxy
sudo cp /etc/haproxy/haproxy.cfg{,.bak} # backup the original config file
sudo bash -c 'cat << EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 148571-web-01 54.237.32.137:80 check
    server 148571-web-02 35.153.231.48:80 check
EOF'

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy service
sudo service haproxy restart
