#!/usr/bin/env bash
# Update package lists

sudo apt-get update

# Installing HAproxy
sudo apt-get -y install haproxy

# Configuring HAproxy to send traffic to web-01 and web-02 using round-robin algorithm
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 148571-web-01 54.237.32.137:80 check
    server 148571-web-02 35.153.231.48:80 check
EOF

# Enabling HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restarting HAproxy service
sudo systemctl restart haproxy.service
